#!/bin/bash
echo "After serve"
cd /home/angular/webapps/www/parking/
sudo npm install -g @angular/cli
sudo ng build 2>&1 | sudo tee /home/angular/webapps/logs/parking/ng_build_log.txt
sudo npm install 2>&1 | sudo tee /home/angular/webapps/logs/parking/npm_log.txt
