#!/bin/bash
echo "After serve"
cd /home/angular/webapps/www/parking/
echo "install angular cli"
sudo npm install -g @angular/cli
echo "install dependency"
sudo npm install 2>&1 | sudo tee /home/angular/webapps/logs/parking/npm_log.txt
